### ISSUE TITLE
Color red and blue byte swapped in Profiler

### ISSUE THREAD

**Issue by jeslaspravin** [wolfpld/tracy#515] opened 2023-01-22 15:15 UTC
I noticed this strange bug. When sending a message with the color `Red` to the profiler(for example using `TracyMessageLC`) the color being sent is displayed in Profiler such that the R byte gets swapped with the G byte and will be displayed as `Blue`

Below is the screenshot of `QueueMessageColor` that is being enqueued from `TracyClient`
<img width="431" alt="image" src="https://user-images.githubusercontent.com/22360874/213923169-40f3e941-0190-4549-b5a4-f9b496d93411.png">

Below is the screenshot of the `Profiler in master`
<img width="626" alt="image" src="https://user-images.githubusercontent.com/22360874/213923230-e3534178-c813-47ce-999c-34912741d0cf.png">

I have raised a pull request here [PR](https://github.com/wolfpld/tracy/pull/514). Please feel free to ignore the PR if it is incorrect in any way.

Below is the screenshot of the `Profiler in Fixed PR`
<img width="623" alt="image" src="https://user-images.githubusercontent.com/22360874/213923252-29adf81f-fe7b-4153-9fb3-0da34df4de5b.png">

### Change in functions
* Worker::AddSourceLocation
* Worker::ProcessZoneColor
* Worker::ProcessMessageColor
* Worker::ProcessMessageLiteralColor

**Comment by wolfpld** [comment] 2023-01-22 23:54
Duplicate of #514.

**Closed by wolfpld** 2023-01-22 23:54 UTC
