### ISSUE TITLE
Undocumented dependency on Linux

### ISSUE THREAD

**Issue by Krzmbrzl** [wolfpld/tracy#299] opened 2021-12-17 10:33 UTC
I am building the tracy profiler (server) on Linux and am following the instructions from the manual. I installed the listed dependencies for Unix but was getting unresolved includes for `tbb/*` files. I had to additionally install the `libttb-dev` from the Ubuntu repos in order to be able to build the program.
Maybe this was a dependency that was forgotten to explicitly list in the docs?

If someone points me at where the source for the docs live, I could create a PR to add this info to it.

**Comment by wolfpld** [comment] 2021-12-17 10:35
Duplicate of #239.

**Closed by wolfpld** 2021-12-17 10:35 UTC
