### ISSUE TITLE
Feature Request: Support for multiple clients

### ISSUE THREAD

**Issue by murphyeoin** [wolfpld/tracy#734] opened 2024-02-22 00:55 UTC
Hello,
we have a use case where we have multiple client processes contributing to different parts of a single output. They are all generating tracy trace data. Frame numbers/ids are synchronized between all of processes. We would like to be able to see all of the trace data in a single tracy timeline. There are a few steps here:

1. uniquely namespace the data from each process/client
2. support listening to and handling data from multiple clients

One Implementation suggestion: 
Create a "mixer" or "relay" daemon that uses multiple Tracy Workers to listen to multiple clients, and passes the data from the multiple clients to a single tracy server. This would involve - amongst other tasks.. rewriting some of the Tracy Worker code to be thread-safe (assuming multiple threads are needed). The daemon would need some sort of UI (possibly the existing connection UI?) or configuration so it knows which clients to connect to.

Wondering if anyone has thought about this before, whether it's a practical idea (or not) and what a good way to approach it is.

 It is related somewhat to https://github.com/wolfpld/tracy/issues/203 (doing this work would make #203 fairly trivial I think).
 
 Thanks for listening

**Comment by wolfpld** [comment] 2024-02-22 10:17
Duplicate of #471.

**Closed by wolfpld** 2024-02-22 10:17 UTC
