### ISSUE TITLE
Issues with DX12 zones

### ISSUE THREAD

**Issue by apiva** [wolfpld/tracy#227] opened 2021-05-28 11:45 UTC
Hi, first of all thank you for your work on this amazing tool. We're integrating Tracy in our game engine for both CPU and GPU profiling.

Initially we started adding Tracy DX12 zones to some of our rendering systems - like postprocessing - and we didn't run into any issue at all. Lately we've tried to profile our main scene rendering and we've started running into some issues, mainly with the server application.

If we pause the data collection but we keep the game open, we see zones flickering:

https://user-images.githubusercontent.com/5911005/119977408-ae0e6a00-bfb8-11eb-9570-1942cb6b3cc2.mp4

If we then close our game, we still see zones disappearing whenever we zoom in and out:

https://user-images.githubusercontent.com/5911005/119977585-ed3cbb00-bfb8-11eb-8c0d-dbdc420ec9da.mp4

The only thing I can think of is that, while our postprocessing rendering code (say, a `buildPostprocess()` function) is called just once, so it will lead to a single zone with a unique source location and literal string, our main scene rendering code (say, a `buildScenePass(const PassType&)`) is called multiple times. We've tried many things, like using always the same literal string or instantiating `D3D12ZoneScope` ourselves passing every time a different string (both static- or heap- allocated) without any result.

Please note that our renderer is multithreaded, so we're creating command lists (and issuing GPU zones) from multiple threads at once. By my _very cursory_ look at `tracy::D3D12QueueCtx`, it doesn't seem to be completely thread-safe, for example what happens if `tracy::D3D12QueueCtx::NextQueryId()` gets called by two threads at exactly the same time, since `m_queryCounter` is not atomic? Anyway I tried to add a mutex to `D3D12ZoneScope` methods but it didn't fix the problem either.

Thank you, I'm available for any further information.

**Comment by wolfpld** [comment] 2021-05-28 11:53
The issues you see stem from unreliability of GPU timer readings. The stream of events, which is linear in time, is poisoned by invalid time stamps, which break sort order. This makes search algorithms find essentially random events instead of the right ones.

You might get better results with different hardware and/or drivers.

**Comment by apiva** [comment] 2021-05-31 08:29
Hi Bartosz, thank you for your time answering this, but I don't think that's the problem. Aside the fact that we've already tried it on different hardware, with the same results, the behaviour of the bug is very consistent: the zones that we've put for postprocessing are always rock solid, and even certain zones for our main passes (ZPrepass never flickers, GBuffer always does).

I've tried googling for this problem, and in general I've searched for examples of Tracy GPU integrations with games, but I've only found a few examples using OpenGL. Could this be a problem limited to DX12? Thank you.

**Comment by wolfpld** [comment] 2021-05-31 21:11
> the behaviour of the bug is very consistent: the zones that we've put for postprocessing are always rock solid, and even certain zones for our main passes (ZPrepass never flickers, GBuffer always does).

The consistency you are observing might be a side effect of the workloads you are measuring -- how many zones are in use, how much time they take to complete, etc. The corruption due to bad timestamps can also be easy to miss, if you are not looking carefully. This is my general experience, but I don't know the true cause here, so you might be on to something.

> Could this be a problem limited to DX12?

Certainly not, as I have seen it also on OpenGL.

In OpenGL ES (and in Direct3D 11, I believe, but I don't use it) you have a concept of a "disjoint query". Quoting from https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_disjoint_timer_query.txt:

```
    In order to know if the value returned from GetIntegerv or GetQuery is valid
    GPU_DISJOINT_EXT needs to be used to make sure the GPU did not perform any
    disjoint operation. This can be done through GetIntegerv by using GPU_-
    DISJOINT_EXT for <pname>. <params> will be filled with a non-zero value if
    a disjoint operation occurred since the last time GetIntegerv was used with
    GPU_DISJOINT_EXT. A zero value will be returned if no disjoint operation
    occurred, indicating the values returned by this extension that are found
    in-between subsequent GetIntegerv calls will be valid for performance
    metrics.

    Disjoint operations occur whenever a change in the GPU occurs that will
    make the values returned by this extension unusable for performance 
    metrics. An example can be seen with how mobile GPUs need to proactively
    try to conserve power, which might cause the GPU to go to sleep at the 
    lower levers. This means disjoint states will occur at different times on
    different platforms and are implementation dependent. When the returned
    value is non-zero, all time values that were filled since the previous 
    disjoint check should be considered undefined."
```

Neither the desktop OpenGL, nor Vulkan have such concept in their APIs. The documentation for Direct3D 12 states that disjoint queries are no longer available. Quoting from https://docs.microsoft.com/en-us/windows/win32/direct3d12/queries:

>The following query types are no longer present in Direct3D 12, their functionality being incorporated into other processes:
>(...)
>Disjoint timestamp queries - GPU clocks can be set to a stable state in Direct3D 12 (see the Timing section). GPU clock comparisons are not meaningful if the GPU idled at all between the timestamps (known as a disjoint query). With stable power two timestamp queries issued from different command lists are reliably comparable. Two timestamps within the same command list are always reliably comparable.

Enabling stable state has several limitations which make it hard to use, as described at https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-setstablepowerstate:


>Do not call this method in normal execution for a shipped application. This method only works while the machine is in developer mode. If developer mode is not enabled, then device removal will occur.
>(...)
>A stable power state typically fixes GPU clock rates at a slower setting that is significantly lower than that experienced by users under normal application load. This reduction in clock rate affects the entire system. Slow clock rates are required to ensure processors don’t exhaust power, current, and thermal limits. Normal usage scenarios commonly leverage a processors ability to dynamically over-clock. Any conclusions made by comparing two designs under a stable power state should be double-checked with supporting results from real usage scenarios.

**Comment by wolfpld** [comment] 2021-06-04 23:54
Digging a bit deeper, this time into Mesa driver implementation. The 36-bit precision of timestamps is indeed confirmed by the code:

`src/intel/common/intel_measure.c:#define TIMESTAMP_BITS 36`

A comment in `src/mesa/drivers/dri/i965/brw_context.c` shines some light on the implementation details:

```
   /* The timestamp register we can read for glGetTimestamp() is
    * sometimes only 32 bits, before scaling to nanoseconds (depending
    * on kernel).
    *
    * Once scaled to nanoseconds the timestamp would roll over at a
    * non-power-of-two, so an application couldn't use
    * GL_QUERY_COUNTER_BITS to handle rollover correctly.  Instead, we
    * report 36 bits and truncate at that (rolling over 5 times as
    * often as the HW counter), and when the 32-bit counter rolls
    * over, it happens to also be at a rollover in the reported value
    * from near (1<<36) to 0.
    *
    * The low 32 bits rolls over in ~343 seconds.  Our 36-bit result
    * rolls over every ~69 seconds.
    */
   ctx->Const.QueryCounterBits.Timestamp = 36;
```

Note that the above is for BRW (Broadwell) uarch, which may, or may not be applicable to the hardware in use, which is CFL (Coffee Lake) uarch. Also note that here the timestamp query value is properly set.

Grepping for `QueryCounterBits` shows that only the `brw_context.c` in the `i965` driver sets this value. The `i965` driver is in use also for CFL:

`include/pci_ids/i965_pci_ids.h:CHIPSET(0x3EA8, cfl_gt3, "CFL GT3", "Intel(R) Iris(R) Plus Graphics 655")`

Other than that, the only other place where `QueryCounterBits.Timestamp` is set seems to be the generic initialization function:

`src/mesa/main/queryobj.c:   ctx->Const.QueryCounterBits.Timestamp = 64;`

**Comment by wolfpld** [comment] 2021-06-09 20:15
To make things more fun for everyone involved, the time stamp readings reset not only when the counter overflows. Rarely the counter is zeroed in midst of the cycle. With the driver and hw mentioned above this seems to be happening rather reliably at around 25 second mark.

**Comment by wolfpld** [comment] 2022-07-03 11:13
This is not an issue that can be fixed in Tracy.

**Closed by wolfpld** 2022-07-03 11:13 UTC
