### ISSUE TITLE
Support for instumenting code that gets unloaded at runtime

### ISSUE THREAD

**Issue by GavinCostello** [wolfpld/tracy#95] opened 2020-08-15 21:01 UTC
Apologies if I've just missed something here, but from the looks of it we currently can't instrument code that gets unloaded due to the way that SourceLocationData is embedded at the point where macros like ZoneNamed# etc are used.

The SourceLocationData is then referenced directly in the ScopedZone item (srcloc)

If the module is unloaded before that zone is processed, which can happen due to the profiler not being attached (with on-demand off), or can even happen with the profiler attached if the module is unloaded shortly after enqueueing the zone... then this SourceLocationData pointer becomes invalid and is pointing into unloaded-module-memory.

Attempting to access this inside Profiler::SendSourceLocation will then segfault trying to read srcloc->name etc.

One proposed solution would be to allocate SourceLocationData on the heap (still just once) and copy the filename/function/name into it (as those static strings will also be unloaded). These can then be pushed onto a list and kept alive for the duration of the runtime and just be cleaned up at shutdown.
It incurs a little extra cost the first time it's encountered and perhaps more-unfortunately potentially quite a bit more memory, but this would allow code to be unloaded.

This could most-easily be implemented as just a separate set of macros for ZoneNamed etc, with 'Dynamic' or something in the name, that handle the dynamic part of the allocation as well as pushing these objects into a global list to be cleaned up on shutdown. Code could then automatically use this version of the macros if a specific define is set, which they can specify for modules they expect to be unloaded, making it pretty seamless.

Just my 2-cents worth :)

**Comment by wolfpld** [comment] 2020-08-15 21:17
Your analysis of the problem is spot-on. This is also an issue for symbol retrieval.

For now you can either never unload modules, or use the C API, which allows allocation of source location data for each instance of a zone (you can wrap this functionality into your own RAII wrappers).

As for the dynamic variant of the macros, I'm not sure how the initialization should be performed. Estimating additional cost, there will be a branch checking if the data should be initialized, so it's not a one-time encumberance. The memory requirements will be negligible. Cleanup may be ignored, there's no need to free data that is about to be freed by the OS anyway.

**Comment by GavinCostello** [comment] 2020-08-15 22:08
So here's a version I just bodged together as an example, but I gave it a quick test and it works in my test-case; I load a module, call a function that adds a scoped zone, then on returning from the function I immediately unload the module.
The data appears as-intended.

So step 1 is to change the SourceLocationData structure to have an explicit constructor that does the copying, something like this:

`    struct SourceLocationData
    {
        const char* name;
        const char* function;
        const char* file;
        uint32_t line;
        uint32_t color;

        SourceLocationData(const char* pcName, const char* pcFunction, const char* pcFile, uint32_t uiLine, uint32_t uiColor)
        {
            {
                if (pcName)
                {
                    size_t uiNameLen = strlen(pcName);

                    char* pDynamicName = (char*)malloc(uiNameLen + 1);
                    if (pDynamicName)
                    {
                        memcpy(pDynamicName, pcName, uiNameLen);
                        pDynamicName[uiNameLen] = 0;
                    }
                    name = pDynamicName;
                }
                else
                {
                    name = nullptr;
                }
            }

            {
                
                if (pcFunction)
                {
                    size_t uiFuncLen = strlen(pcFunction);
                    char* pDynamicFunc = (char*)malloc(uiFuncLen + 1);
                    if (pDynamicFunc)
                    {
                        memcpy(pDynamicFunc, pcFunction, uiFuncLen);
                        pDynamicFunc[uiFuncLen] = 0;
                    }
                    function = pDynamicFunc;
                }
                else
                {
                    function = nullptr;
                }
            }

            {
                
                if (pcFile)
                {
                    size_t uiFileLen = strlen(pcFile);
                    char* pDynamicFile = (char*)malloc(uiFileLen + 1);
                    if (pDynamicFile)
                    {
                        memcpy(pDynamicFile, pcFile, uiFileLen);
                        pDynamicFile[uiFileLen] = 0;
                    }
                    file = pDynamicFile;
                }
                else
                {
                    file = nullptr;
                }
            }

            line = uiLine;
            color = uiColor;

            //TODO: Push this object onto a list somewhere in a thread-safe way, for cleanup on shutdown!
        }
    };`

Then you just change the macros (or provide new ones) so that they 'new' the struct on the heap and invoke the constructor.
Here's one example:
`#  define ZoneNamedN( varname, name, active ) static const tracy::SourceLocationData* TracyConcat(__tracy_source_location,__LINE__) = new tracy::SourceLocationData( name, __FUNCTION__,  __FILE__, (uint32_t)__LINE__, 0 ); tracy::ScopedZone varname( TracyConcat(__tracy_source_location,__LINE__), TRACY_CALLSTACK, active );`

And that's it... no other changes required. The first time the ZoneNamedN line is hit it will dynamically allocate the data and copy the contents into it. There's a TODO in there to push it into a thread-safe queue or linked-list too, I think you have one of those already.
All other code using the tracy::SourceLocationData can be left as-is, as it'll now persist for the lifetime of the program.

And at some point on shutdown you'll want to call a function to go through that linked-list of SourceLocationData's and delete all the memory allocated to them. It's true that the OS is going to free the memory anyway, but this is a niceness so that any memory tools (including custom ones made by people for their engines) don't report them as being leaks.

This does have the caveat that the modules need to have a shared heap for those objects so they're not allocated on one heap and free'd on another, although you could just provide a function like `TRACY_API tracy::SourceLocationData* TracyAllocSourceLocationData()` that does the allocation within the 'profiler' module (the one the .cpp links into) so you don't have to worry about that either.

As an additional little niceness, you can still keep using the existing macros as-is for any that aren't 'dynamic' as there were no changes to the structure of the code, just how its allocated (embedded or heap) and how the data is set (initialiser list or constructor) which is all controlled within the macros.

**Comment by GavinCostello** [comment] 2020-08-15 22:15
Oh... you'd want to do something similar for the LockMark macro too. Basically anything that's going to reference those `__FILE__` or `__FUNCTION__` macros or that are otherwise going to create embedded SourceLocationData objects :)

**Comment by wolfpld** [comment] 2020-08-15 22:18
The constructor/initializer list approach is very nice, I like it.

I have added some words of caution to the manual. This problem is not limited to zones or locks, but also to frame names, plot names, and probably something else too.

**Comment by GavinCostello** [comment] 2020-08-15 22:23
Yeah just after I closed that last message I thought "oh, and anywhere else you let them specify a string, such as Messages and named-frames"... I'm sure you have better coverage on all those bits than I do though, have only been integrating this for 4 days.

Aside from running into a few issues like the above it has been pretty seamless though, and it's really nice to run my linux build in a VM and connect my windows Tracy profiler to it, really makes the workflow very nice!

**Comment by GavinCostello** [comment] 2020-08-15 22:44
A generic-ish solution to getting around the issue with all the other places where strings are passed raw and stored as uint64 addresses might be to do something like this:

`#define FrameMarkStart( name ) static char* TracyConcat(pooledName_,__LINE__) = TracyAddOrFindPooledString(name); tracy::Profiler::SendFrameMark( TracyConcat(pooledName,__LINE__), tracy::QueueType::FrameMarkMsgStart );`

In that way, by adding a TracyAddOrFindPooledString(...)-like function you could have a singular place that finds or creates a new copy of each of the strings and the rest of the code can continue to reference them as uint64 then... plus you've got a singular place to clean them up later. So that might be a nice "only really touches the macros" solution to this issue that can be used across most of these scenarios.

I'm going to stop faffing around and bugging you with this now, for the time being I can limit my instrumentation to modules that don't unload or just make local changes, but it'd be great to see support for unloadable code like this in a future release.

Thanks for all the great work so far though, it's nice to be able to get such a comprehensive profiler in pretty early-on and have that visibility of performance during development 😄

**Comment by wolfpld** [comment] 2020-08-16 14:02
The solution as proposed was not valid, as source locations are distinguished by their address, so allocating multiple identical source locations would result in separate entries being displayed by the profiler.

A new set of `ZoneTransient` macros was added, which uses the already existing "allocated source location" functionality. This resolves the main issue here.

User manual is now explicitly stating the undesirable effects of unloading modules. In some cases remedies are possible, e.g. by replacing `TracyMessageL` with `TracyMessage`. In other cases (plots, frame names, code retrieval) there is currently no solution other than not unloading modules.

**Comment by GavinCostello** [comment] 2020-08-16 15:24
I'm not sure why it would allocate multiple identical source locations, the fact that it's malloc'd doesn't change the fact that it's static so should still just allocate the first time it's encountered (with the normal double-lock thread-safeties around static member initialisation that applies to other statics)... so for each unique line you should still just get one SourceLocationData that's re-used by everything that encounters it from that point onwards.

**Comment by wolfpld** [comment] 2020-08-16 15:33
From `man dlopen`:

**RTLD_NODELETE** (since glibc 2.2)
    Do not unload the library during dlclose(). Consequently, the library's static variables are not reinitialized if the library is reloaded with dlopen() at a later time.

**Comment by GavinCostello** [comment] 2020-08-16 15:44
Oh I see, I was thinking more about unloading than re-loading but that's a really good catch!

Loading the modules with RTLD_NODELETE would allow those statics to persist across multiple close/opens, otherwise as you say we would indeed end up with multiple addresses for the same callstack upon the first encounter after each reload!
I guess an alternate approach might be to create a unique hash off of the file/location information and group by that.

I'm wondering now how something like hot-reload would play with this system where you've deliberately changed the code too, I guess there's no way to make that play nicely 😞

Interesting how deep this rabbit hole goes!

**Comment by wolfpld** [comment] 2020-10-21 21:26
> In other cases (plots, frame names, code retrieval) there is currently no solution other than not unloading modules.

A workaround for this has been added to the manual.

Closing the issue, as everything should now be properly documented. Feel free to reopen if you'd find any missing things to add.

**Closed by wolfpld** 2020-10-21 21:26 UTC
