### ISSUE TITLE
Usability issues when lots of threads with sparse data are present in a trace

### ISSUE THREAD

**Issue by nsubtil** [wolfpld/tracy#258] opened 2021-09-02 18:49 UTC
We have traces that, for various reasons (big multi-socket machines, lots of short-lived threads) end up with hundreds of individual threads identified by Tracy, on the order of 700-1000+.

A lot of these threads have only one event (sometimes a small handful, typically clustered together in time). However, their presence makes scrubbing the timeline very difficult, as they cause sudden dramatic changes in vertical scaling in the UI. Disabling threads is an option, but the UI to do so is a bit clunky --- we often want to have 64-128 threads enabled, which still requires a lot of clicking on checkboxes.

Would love to find a way to make this experience less painful, though I don't know what the right solution is.

One simple solution could be an option to keep all threads visible in the timeline, regardless of whether the current view contains any events for those threads.

Another helpful change would be to allow enabling/disabling a range of threads in the options window with a few clicks (maybe a list box instead of check boxes, where we could select ranges easily? would probably require some sorting options for the list to go along with it).

**Comment by wolfpld** [comment] 2021-09-02 19:18
> lots of short-lived threads

Typically you would want to use some kind of thread pool and a task system in such cases. It would not only minimize the number of reported threads, but also make the application more performant, by removing time needed to spin up and down multiple threads.

> sudden dramatic changes in vertical scaling in the UI.

Yes, this is a know issue, which also manifests itself in different use cases. A good solution is non-trivial here.

> One simple solution could be an option to keep all threads visible in the timeline, regardless of whether the current view contains any events for those threads.

Options -> Draw empty labels.

> maybe a list box instead of check boxes, where we could select ranges easily?

I don't think this is achievable with the available controls and it would require creating a custom list, along with some way to instruct the user how it works, etc.

**Comment by nsubtil** [comment] 2021-09-02 19:35
> > One simple solution could be an option to keep all threads visible in the timeline, regardless of whether the current view contains any events for those threads.

> Options -> Draw empty labels.

I tried this, but it still causes threads in the timeline to change width depending on whether they have events visible or not, so we still have the same problem --- the vertical rubber-banding still triggers and the changes in vertical placement are large enough that the data we need to look at scrolls off screen as we scrub.

**Comment by wolfpld** [comment] 2021-09-02 19:47
Yes, these are the "different use cases" I have mentioned.

**Comment by wolfpld** [comment] 2022-07-03 11:18
Closing as duplicate of #286 (it's easier to understand the problem with the video).

**Closed by wolfpld** 2022-07-03 11:18 UTC
Labels: bug, enhancement
