### ISSUE TITLE
client dumping to file directly

### ISSUE THREAD

**Issue by ShuangLiu1992** [wolfpld/tracy#162] opened 2021-01-12 17:09 UTC
is it possible to dump the trace data directly to a file by the client by choice?
this would be useful in applications where networking is difficult (emscripten compiled program inside brwoser)

**Comment by wolfpld** [comment] 2021-01-12 17:12
See https://github.com/wolfpld/tracy/issues/157#issuecomment-752087159.

**Comment by wolfpld** [comment] 2021-01-15 21:35
Duplicate of the above.

**Closed by wolfpld** 2021-01-15 21:35 UTC
